export const RANDOM_ACTION_TYPES = {
  FETCH_RANDOM_START: "random/FETCH_RANDOM_START",
  FETCH_RANDOM_SUCCESS: "random/FETCH_RANDOM_SUCCESS",
  FETCH_RANDOM_FAILED: "random/FETCH_RANDOM_FAILED",
  DATA_RANDOM_POP: "random/DATA_RANDOM_POP_LAST_ITEM",
};
